accounts/urls.py
from django.urls import path
from .views import  CreateUser, LogIn, Logout
from django.contrib.auth.decorators import login_required


app_name = 'accounts'

urlpatterns = [
    path('create/', CreateUser.as_view(), name='create-user'),
    path('login/', LogIn.as_view(), name='login-user'),
    path("logout/", Logout.as_view(), name="logout"),







]

bewegungs_melder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('accounts/', include('accounts.urls'))

]

homepage/urls.py
from django.urls import path
from .views import HomePage

app_name = 'homepage'

urlpatterns = [
    path('',HomePage.as_view(), name='homepage'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.password_validation import validate_password
# Create your models here.

class UserManager(BaseUserManager):
    """
    The class is to override the django admin system its inheritance from BaseUserModel inthe class we have 2 definitions 
    the first one is to create a normal user by normal user  and to create a superuser that can effect the permission after that if needed

    """
    def create_user(self, email, first_name, last_name , password=None):
        """
        create a normal user the is staff field is set to false 
        """
        if not email:
            raise ValueError ( 'Email field is required')

        user = self.model(
            email = self.normalize_email(email)
        )
        user.first_name= first_name
        user.last_name = last_name
        #user.is_staff = False
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password ):
        """
        the super user is an Admin and can modify all operations in the App(Delete, update, create)
        """
        user = self.create_user(
            email, 
            first_name=first_name,
            last_name=last_name,
            password=password,

            )
        user.is_staff=True
        
        user.save(using=self._db)
        return user

class User (AbstractBaseUser):
    """
    the class inheritance from the BaseUser  and will create a Table in the database for the user 
    the password is required by default in django and thats the reason why we donot have here an field for password
    the user name field is the email field and the required fielder are (email, first_name, last_name and the password)
    """
    email = models.EmailField(max_length=255, unique=True, blank=False, null=False)
    first_name = models.CharField(max_length=122, blank=False, null=False)
    last_name = models.CharField(max_length=122, blank=False, null=False)
    active = models.BooleanField(default=True)

    is_staff = models.BooleanField(default=False, blank=True, null=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()
  
    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def has_perm(self, perm, obj=None):
        return True    

    def has_module_perms(self, app_label):
        return True         

homepage/models.py
from django.db import models

# Create your models here.

sensor/models.py
from django.db import models
import datetime
# Create your models here.

class Sensor(models.Model):

    movement = models.BooleanField(default=True)
    movment_date = models.DateTimeField(default=datetime.datetime.now())

    def __str__ (self):
        return str(self.movment_date)

accounts/forms.py
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class UserLoginForm(forms.ModelForm):
    """
    the Class inheritance from django model form and to log a user in the user need the user email and the password to log in  
    """
    password = forms.CharField(label='Password', widget=forms.PasswordInput)    
    class Meta:
        model = User
        fields = ['email', 'password']

class UserCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields
    """
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(label='Password',required=True,validators=[validate_password] ,widget=forms.PasswordInput())
    first_name = forms.CharField(label='First Name',required=True, widget=forms.TextInput())
    last_name = forms.CharField(label='Last Name',required=True, widget=forms.TextInput())



    class Meta:
        model = User
        fields = ('email','password','first_name','last_name' )

    def save(self,commit=True):
        """
        Save the provided password in hashed format
        """
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])        
        if commit:
            user.save()
        return user
    

"""
class UserUpdateForm(forms.ModelForm):
    A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    
    #password = ReadOnlyPasswordHashField()
    email = forms.EmailField(label='Email', required=True)
   # password = forms.CharField(label='Password',required=True, widget=forms.PasswordInput())
    first_name = forms.CharField(label='First Name',required=True, widget=forms.TextInput())
    last_name = forms.CharField(label='Last Name',required=True, widget=forms.TextInput())
    is_staff = forms.BooleanField(label='Staff',required=False, widget=forms.CheckboxInput())


    class Meta:
        model = User
        exclude = ('last_login','password','active')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


"""

accounts/views.py
from django.shortcuts import render, redirect

from django.views.generic import ListView, CreateView, DetailView
from .models import User
from django.views.generic import View
from django.contrib.auth.models import auth
from .forms import UserLoginForm, UserCreationForm
from django.contrib import messages



class CreateUser(CreateView):
    template_name = 'accounts/create_user.html'
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, self.template_name, {'form':form})

    def post(self, request,*args, **kwargs):
        form = UserCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('.')
        return render(request, self.template_name, {'form':form})
        

class LogIn(View):
    """
    the class is to handel get and post method when a user want to login
    """
    template_name = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        """

        :param request: Url get request
        :return: will return an empty form (loginForm)
        """
        form = UserLoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        """

        :param request: Url post request
        :return: will let the user login in case all the information in the form is valid
        """
        form = UserLoginForm(request.POST or None)
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(self.request, user)
            return redirect('homepage:homepage')
        else:
            messages.info(request, "invalid name or password")
            return redirect('accounts:login-user')
        return render(request, self.template_name, {'form': form})


class Logout(View):
    """
    the class is to logout a User
    """
    def get(self, request):
        """

        :param request: URl get request
        :return: logout
        """
        auth.logout(request)
        return redirect('accounts:login-user')

homepage/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.

class HomePage(View):
    """
    the class inheritance from a generic view and it is a normal view to create the homepage (landing page)
    """
    template_name = 'homepage/home_page.html'

    def get (self, request, *args, **kwargs):
        return render(request, self.template_name)

sensor/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/create_user.html
{% extends 'base.html' %}

{% block title %} Create User {% endblock %}
{% load bootstrap3 %}
{% block content %}

<h2>Create user</h2>
<div class="container">
    <form action="." method='post' class="form big-form ">
        <div class="form-group">
            {% csrf_token %}
            {% bootstrap_form form %} 
            {% for msg in messages %}
            <p style=color:red;>{{msg}}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary right_buttons">Create</button>
    </form>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}User Login {% endblock %}
{% load bootstrap3 %}
{% block content %}

<h2>User login</h2>
<div class="container">
    <form action="." method='post' class="form big-form ">
        
        <div class="form-group">
            {% csrf_token %}
            {% bootstrap_form form %} 
            {% for msg in messages%}
            <p style=color:red;>{{msg}}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary right_buttons">LogIn</button>
    </form>


{% endblock %}

bewegungs_melder/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link type="text/css" rel="stylesheet" href="{% static 'styles/index.css' %}">

    <title> {% block title %} {% endblock %} </title>
</head>

<body>

    <div class="container-fluid">
        {% include 'navigation.html' %}
        <div class="container">

        {% block content %}
        {% endblock %}

        <footer style="color:blue;">
            &copy; Created By Group 2 
        </footer>
    </div>
</div>
        
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    {% block js %}

    {% endblock %}


</body>

</html>

bewegungs_melder/templates/navigation.html
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Bewegungs Sensor</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'homepage:homepage' %}">Home</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Our Products</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="#">{{user.email}}</a></li>  
            <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-in"></span> LogOut</a></li>
              
              {% else %}
            <li><a href="{% url 'accounts:create-user' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="{% url 'accounts:login-user' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            {% endif %}

          </ul>
        </div>
      </nav>

homepage/templates/homepage/home_page.html
{% extends 'base.html' %}

{% block title %}
Homepage
{% endblock %}

{% block content %}
<p>Home page</p>


{% endblock %}